# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368f489d41eb93255ebc25b80e72772860229e207e7e9b7a0a733ed205e924d2678c07a5e979bb54b8e8a3fd501c4d39d61f42c41686e61701111da3fb8e9b35

test:
  secret_key_base: 00e7b309f75aefae4970952da1a9f97cade6e912f4921fb83cee093c8d3169222a71b2c941e057c085436240ec970c8da7b0a9919189d948f48e12b70be03cf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
